### ISSUE TITLE
This is very interesting. Not filing an issue here, I open a discusion

### ISSUE THREAD

**Issue by Madeindreams** [bytenode/bytenode#104]
I have been looking for a way to run some bytecode and I think your example is leading to the right path.

I wonder if you would have any idea how I could pass encoded argument to the bytecode?

Example;

```
let name[]

function setName(name){
name.push(name)
return true
}

```

If I was to compile this code in bytecode. 
How could I pass argument directly to the bytecode to evaluate at execution time? 

Let's make some javascript smart contract!?

**Comment by OsamaAbbas** [comment]
Let me ask first, are you aware that this project is built on top of Node.js exclusively?

**Comment by Madeindreams** [comment]
Yes I am. This is what i like about it.

I want to reproduce Ethereum process with Javascript under NodeJS

If i could store the bytecode on the blockchain and then run it with arguments for runtime. it would be like a smart contract in javascript

**Comment by Madeindreams** [comment]
The Ethereum process work like that.

You write a contract and compile it to deploy it on the blockchain.
Every Node have a copy of the blockchain and can run the bytecode with the EVM for Ethereum.
NodeJS do the same with JVM.

So a user can ask a node to run that bytecode with arguments.

The program get executed and rewrited to the chain with the new Data.

So i need to figure out how to pass an argument to the bytecode to execute the code.

**Comment by Madeindreams** [comment]
Maybe have a look at what I am trying to de here;

Based on your code.

https://stackoverflow.com/questions/66279575/how-to-retrieve-the-bytecode-of-nodejs-vm-state-javascript-smart-contract-exper

I can I retrieved the, I guess "cached stated", of the VM instance so the next time i execute the bytecode the name is still in there?

**Comment by OsamaAbbas** [comment]
That is a tricky task. It needs some reflection to be honest.

I think I get what you want to achieve. But I don't have a complete answer yet.

By the way, the `bytenode.runBytecode(bytecodeBuffer)` function will [run in the current context](https://github.com/OsamaAbbas/bytenode/blob/734ec0c7788992c44689cb7161b3dca1071b673e/index.js#L108). So, if you have a buffer that would define some functions, you will be able to run it, then you can call these functions.

Please note that the generated bytecode must be run with the exact same version (with the same arch and os too) that was used to generate it in the first place.

**Comment by Madeindreams** [comment]
`Please note that the generated bytecode must be run with the exact same version (with the same arch and os too) that was used to generate it in the first place.`

I have tryed to save the bytecode to a file and relaod it but without success. And now that you mention that it raises more questions. This kinda go against the VM purpose but i guess it's because we generated that bytocode within our environement and not within the VM. So would I need to generate the bytecode inside the VM rather then Nodejs?

**Comment by OsamaAbbas** [comment]
The sole purpose of this project is to help Node.js developers to protect their source code if they don't want to distribute it in a plain text form. Due to the v8 limitation (which is what Node.js uses in `createCacheData` function), it must be run with the exact same version as explained in my previous comment.

So, `bytecode` here is not the same as in Java for example.

> This kinda go against the VM purpose but i guess it's because we generated that bytocode within our environement and not within the VM. So would I need to generate the bytecode inside the VM rather then Nodejs?

If by `VM` you mean the Ethereum Virtual Machine, then I don't know how could this be even possible. Also, I don't have any experience with Ethereum at all.
