### ISSUE TITLE
Will this work for Electron renderer processes?

### ISSUE THREAD

**Issue by jjeff** [bytenode/bytenode#105]
First off, I'm really excited about this module. Great work! 

From the example, it looks like bytenode will compile Electron's main process files. Is there a way to compile the renderer process files? These may or may not have node enabled, but I'm not sure how they might have file system access. Is there another method for compiling them to bytecode?

Thanks!

**Comment by OsamaAbbas** [comment]
In order to use bytenode, you must have an access to the Node.js' `require` function. So if the render process does not have Node.js enabled, you can't require neither bytenode nor any other node files.

**Comment by jjeff** [comment]
With `nodeIntegration` turned on for an Electron `BrowserWindow`, you do have access to `require()`. I'll see if I can figure it out and maybe I can send you a new example project which compiles the renderer as well.

Thanks.

**Comment by OsamaAbbas** [comment]
There are many issues (or questions) here to show how to compile a renderer process. I will try to find you some of them later.

**Comment by GreedyWhale** [comment]
Yes, it can, this is a demo I wrote, hope it will help you  

[demo](https://github.com/GreedyWhale/electron-react-demo)

The encryption method is here[tools/encode.js](https://github.com/GreedyWhale/electron-react-demo/blob/main/tools/encode.js)
