### ISSUE TITLE
Code Standard

### ISSUE THREAD

**Issue by jjeff** [bytenode/bytenode#113]
To enable easier collaboration, would you like to implement a linter and a code standard for this project? Do you have a standard that you prefer? [Standard](https://standardjs.com) is easy and doesn't require configuration. But there are others that you may prefer.

At minimum, it would remind me to put `;` at the end of every line! 🙂

I could submit a pull request to implement this, if you're open to it.

**Comment by OsamaAbbas** [comment]
Closing this issue now as there is a related pull request which should be merged soon.
