### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by jjeff** [bytenode/bytenode#114]
Would you be interested in a pull request to move this code to Typescript? It should make coding/testing easier and it will also create type definition files for IntelliSense autocompletion for end users.

It's a nice feature to have, but I can understand if you don't want to complicate the workflow.

**Comment by jjeff** [comment]
I was using Typescript in the [electron-bytenode](https://github.com/spaceagetv/electron-bytenode/tree/main/src) module (which is basically an unnecessary rewrite of bytenode), so you can see what it might look like there.

**Comment by OsamaAbbas** [comment]
Closing this issue now as there is a related pull request which should be merged soon.
