### ISSUE TITLE
Running in the current context of an app with a module.

### ISSUE THREAD

**Issue by aarock1234** [bytenode/bytenode#127]
I have been looking into the source for bytenode and was able to modify the runBytecode to support running a module. When I run in the global context I can not access the variables in the module. I would like to be able to call functions inside of the file even when it is compiled as a module.

Ex.
```js
const hello = "https://www.google.com/";

function testfunc(paramater) {
	paramater = paramater + 'hello';
	return paramater;
}

function testfunc2(number, number2) {
	return number * number2;
}

console.log(testfunc(hello))
```

That compiles using:
```js
const bytenode = require('bytenode');

bytenode.compileFile({
    filename: 'encode.js',
    compileAsModule: true
});
```

I sorta hacked something together for the implementation, this is NOT going into production and simply for personal experiments ONLY, please understand this:
```js
const runBytecode = function (bytecodeBuffer) {

  if (!Buffer.isBuffer(bytecodeBuffer)) {
    throw new Error(`bytecodeBuffer must be a buffer object.`);
  }

  fixBytecode(bytecodeBuffer);

  let length = readSourceHash(bytecodeBuffer);

  let dummyCode = "";

  if (length > 1) {
    dummyCode = '"' + "\u200b".repeat(length - 2) + '"'; // "\u200b" Zero width space
  }

  const c = new vm.Script(dummyCode, {
    cachedData: bytecodeBuffer
  })
  c.runInNewContext(global)(module.exports, require, module, __filename, __dirname, process, global);
  console.log(global) // Does not log the functions 'testfunc' and 'testfunc2'
  // Successfully runs and logs the output, though.

  /*if (script.cachedDataRejected) {
    throw new Error('Invalid or incompatible cached data (cachedDataRejected)');
  }*/

  return //script.runInThisContext();
};
```

Any input would help!

**Comment by OsamaAbbas** [comment]
I apologies for the late response. I will look into it and get back to you.

**Comment by aarock1234** [comment]
> I apologize for the late response. I will look into it and get back to you.

Thank you, looking forward to an answer, this problem has been bugging me for a while ha!

**Comment by aarock1234** [comment]
> I apologize for the late response. I will look into it and get back to you.

Any updates? 😄

**Comment by OsamaAbbas** [comment]
> > I apologize for the late response. I will look into it and get back to you.
> 
> Any updates? 😄

Haven't had a chance yet, sorry. I'm assuming it is not urgent, is it?

**Comment by aarock1234** [comment]
> > > I apologize for the late response. I will look into it and get back to you.
> > 
> > 
> > Any updates? 😄
> 
> Haven't had a chance yet, sorry. I'm assuming it is not urgent, is it?

Not urgent, take your time, just curious.

**Comment by OsamaAbbas** [comment]
I looked into what you have written and I did not fully understand what you want to achieve.

If I understood correctly, then the behavior that you want is NOT what plain node.js does.

Feel free to edit and adapt bytenode whatever you see fit. All I'm saying is that is beyond the help that we can offer here.
