### ISSUE TITLE
Test against Node 5.7 (and others?)

### ISSUE THREAD

**Issue by jjeff** [bytenode/bytenode#128]
The Bytenode README file says "It can be used with Node.js >= 5.7.x". However, our new [test.yml file](https://github.com/bytenode/bytenode/blob/master/.github/workflows/test.yml) only tests against Node 12 and 14.

We should probably update that to test against Node 5.7.x… and others? Node 10?

I don't know which versions GitHub supports. I don't which versions are popular.

**Comment by OsamaAbbas** [comment]
I'd rather to remove this line now as it was written in 2018 and only meant to reflect [this fact](https://nodejs.org/dist/latest-v14.x/docs/api/vm.html#vm_new_vm_script_code_options) (open history part to see that The cachedData and produceCachedData was added in v5.7.0).

However, the created cached code needs to be fixed (as in [#L103-L115](https://github.com/bytenode/bytenode/blob/58b2e2b618316357055083783aadcce67a42dcdb/index.js#L103-L115) and [#L125-L130](https://github.com/bytenode/bytenode/blob/58b2e2b618316357055083783aadcce67a42dcdb/index.js#L125-L130)), and this was done by examining v8 source code (specifically [this file](https://github.com/nodejs/node/blob/6a9ec8d9331ee726b26ef8427c42e7571bf31174/deps/v8/src/snapshot/code-serializer.h#L90-L109) for each version of v8). As you can see from my [messy] code, it indicates that we deals with `v8.8` and `v8.9` first, then `v12` to `v15`, finally the rest of node.js version. The "rest" here means exactly: `v10` and `v11` (as far as I can remember). Even if it works with v8.7 or earlier, it is just a coincidence.

So maybe in bytenode v2.0.0 we should change ([#L103-L115](https://github.com/bytenode/bytenode/blob/58b2e2b618316357055083783aadcce67a42dcdb/index.js#L103-L115) and [#L125-L130](https://github.com/bytenode/bytenode/blob/58b2e2b618316357055083783aadcce67a42dcdb/index.js#L125-L130)) to better reflect what it really does (by throwing an error if node.js version is not supported).
