### ISSUE TITLE
Class does not work

### ISSUE THREAD

**Issue by G4den** [bytenode/bytenode#130]
This is the code i am using
```
class Task {
  constructor() {}
}

console.log("Loaded class_test.js");

module.exports = { Task };

```

I am compiling the code with bytenode using this command 
`"bytenode -c ./test_area/class_test.js`

And when running this loader file:
```
const { Task } = require("./class_test.loader");

const t = new Task();
```

I get this error:
```
const t = new Task();
          ^

TypeError: Task is not a constructor
    at Object.<anonymous> (C:\Users\gade1\WebstormProjects\nike-gen\test_area\bytenode_task_test.js:3:11)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

But when running the non compiled version:
```
const { Task } = require("./class_test");

const t = new Task();

```

It works just fine.
I have already read the known limitations, and i can not find any others having the same problem.

Node: v13.13.0
Bytenode: 1.2.1

**Comment by OsamaAbbas** [comment]
I guess you need to require the `.jsc` file directly, not the `*.loader.js` file. The loader file is meant to be as your entry script or so.

```javascript
const { Task } = require('./class_test.jsc');

const t = new Task();
```

**Comment by christopherGr** [comment]
Hello,

Unfortunately I am facing the same issue in my Electron app..

**Main File**
const myClass = require('./myClass.js'); 
either 
const myClass = require('./myClass.jsc'); 
myObject = new myClass();

**Class**
module.exports = class myClass{
	constructor() {
         }
}

Only when compiling with bytenode, I am getting the following error:
object is not a constructor
    at new myClass (VM617 evalmachine.<anonymous>:1)
    at VM617 evalmachine.<anonymous>:1

Thanks in advance!

**Comment by OsamaAbbas** [comment]
I can't reproduce your issue.

Here is my setup:

`./main.js`
```javascript
require('bytenode');

const MyClass = require('./myClass.jsc');

const myObject = new MyClass();

console.log(myObject);
```

`./myClass.js`
```javascript
module.exports = class MyClass {
  constructor () {
    console.log('object created.');
  }
};
```

Then:

```console
$ bytenode --compile myClass.js
$ node main.js
object created.
MyClass {}
```

```console
$ bytenode -v
bytenode 1.3.3
Node 14.17.0
```

**Comment by christopherGr** [comment]
Hello,

I am sorry for the inconvenience... you 're right, it was my fault..
Thank you for this awesome module!

**Comment by absir1949** [comment]
hello. i find a different.

`./main.js`
```
module.exports = class MyClass {
  constructor () {
    console.log('class created.');
  }
};
```

`./test.js`
```
require("bytenode");
const a1= require('./main.js')
const a2= require('./main.jsc')

console.log(a1)
console.log(a2)
```
Then:
```
$ bytenode -c main.js
$ node test.js
```

```
[class MyClass]
[Function: MyClass]
```

can i got a the same output? i want this is a `class` not a `function`
