### ISSUE TITLE
How to use it at vite and electron?

### ISSUE THREAD

**Issue by allran** [bytenode/bytenode#131]
I use the vite program as electron renderer, but I get follow error:
```
SyntaxError: Cannot use import statement outside a module
```
I get [#95](https://github.com/bytenode/bytenode/issues/95) message, i need use 【require】 replace 【import】。

but in the vite, I cann't use require. Is there any way to solve it？

**Comment by OsamaAbbas** [comment]
I have no experience with `vite`, but from their website:

> For production: the default build targets browsers that support native ESM via script tags. Legacy browsers can be supported via the official @vitejs/plugin-legacy - see the Building for Production section for more details.

`bytenode` is used specifically with Node environment, not inside the broweser. (although you can protect your browser code with some tricks, but it is not straight forward).

If you can create a very minimal project with vite and electron, then I can look into how we could fit `bytenode` there.

**Comment by allran** [comment]
I create a small project by CLI, the source at [vite-electron-builder](https://github.com/allran/vite-electron-builder.git), and the branch name is [**_alan_bytecode_**].

You can test like this:
```
//1. get the code
git clone https://github.com/allran/vite-electron-builder.git
cd vite-electron-builder
git checkout alan_bytecode
npm install 

//2. load .ts to .js
npm run precompile

//3. to bytecode
npm run bytenode
```

Then,  the bytenode can work .js at '/packages/main/dist/' and '/packages/preload/dist/'.  But the vite code at  '/packages/renderer/dist/', I get some error:
SyntaxError: Unexpected token 'export'
or:
SyntaxError: Cannot use import statement outside a module
or other.

**Comment by allran** [comment]
@OsamaAbbas Excuse me, after reviewing the code, is there any good way?

**Comment by OsamaAbbas** [comment]
> @OsamaAbbas Excuse me, after reviewing the code, is there any good way, thank you.

I apologize for the late reply. I thought I have replied already!

I keep getting this error:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/vue-tsc/-/vue-tsc-0.0.23.tgz - Not found
npm ERR! 404 
npm ERR! 404  'vue-tsc@https://registry.npmjs.org/vue-tsc/-/vue-tsc-0.0.23.tgz' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/osama/.npm/_logs/2021-05-04T13_58_03_120Z-debug.log
```

**Comment by OsamaAbbas** [comment]
Anyways, vite uses native ES modules in renderer code, which in principle can't be compiled using bytenode. So before compiling your renderer code you have to figure out how to convert it it to the regular commonjs modules that can be loaded using `require` function.

I'm closing this issue for now, as I believe there is not much that we can do with ES modules.
