### ISSUE TITLE
What's the meaning of "readSourceHash" function?

### ISSUE THREAD

**Issue by Zhxhh** [bytenode/bytenode#132]
I just wonder what is the meaning of this function? Why can it work when using "readSourceHash" to produce dummyCode and then pass them as code to "vm.script" function?
```
const readSourceHash = function (bytecodeBuffer) {

  if (!Buffer.isBuffer(bytecodeBuffer)) {
    throw new Error(`bytecodeBuffer must be a buffer object.`);
  }

  if (process.version.startsWith('v8.8') || process.version.startsWith('v8.9')) {
    // Node is v8.8.x or v8.9.x
    return bytecodeBuffer.slice(12, 16).reduce((sum, number, power) => sum += number * Math.pow(256, power), 0);
  } else {
    return bytecodeBuffer.slice(8, 12).reduce((sum, number, power) => sum += number * Math.pow(256, power), 0);
  }
};
```
Thanks in advance :)

**Comment by OsamaAbbas** [comment]
I wrote about this before, check this article: https://medium.com/hackernoon/how-to-compile-node-js-code-using-bytenode-11dcba856fa9

Let me know if you still have a question.

**Comment by Zhxhh** [comment]
> I wrote about this before, check this article: https://medium.com/hackernoon/how-to-compile-node-js-code-using-bytenode-11dcba856fa9
> 
> Let me know if you still have a question.

thanks！！！helps a lot
