### ISSUE TITLE
Electron preload via bytenode if sandbox is enabled

### ISSUE THREAD

**Issue by petef19** [bytenode/bytenode#133]
Hi,

similar to #85, I'm looking to protect the preload script. Procedure outlined in #85 works in general. but fails when `sandbox: true` is set in the `webPreferences`.

I believe this has to do with that with `sandbox` enabled, you don't have Node.JS and the require function can't load the 2nd preload script (when running in a sandboxed renderer).

Any idea how to get the bytenode protected code in a  single preload script ?

Thanks.

**Comment by OsamaAbbas** [comment]
In order to work, bytenode must have an access to Node.js and its require function. Setting `sandbox` to `true` will disable Node.js altogether. So you will no longer be able to use bytenode.

I don't have a workaround for this scenario, though.

**Comment by petef19** [comment]
mentioned this scenario here [https://github.com/electron/electron/issues/28981#issuecomment-831835550](url), hoping that they will add support to define `preload` directly inside `main.js`.
