### ISSUE TITLE
The VM module is getting deprecated in Electron renderer

### ISSUE THREAD

**Issue by gpetrov** [bytenode/bytenode#137]
Seems that the VM module in Electron's renderer process is asking for trouble. So the Electron team is deprecated it.

https://github.com/electron/electron/pull/26087

https://github.com/electron/electron/pull/25910#issuecomment-713197726

Does this means we can't use bytenode no longer in Electron's renderer @OsamaAbbas ?

**Comment by OsamaAbbas** [comment]
It depends on what is meant by removing it from the renderer process.

This concern was reported before here: https://github.com/bytenode/bytenode/issues/107
