### ISSUE TITLE
Got segmentation fault with M1

### ISSUE THREAD

**Issue by blackmiaool** [bytenode/bytenode#142]
I got segmentation fault error when I use M1 to compile the js to jsc and run the jsc on a x86 VPS.
Obviously we must compile on x86 to run on x86.

**Comment by OsamaAbbas** [comment]
This already stated in the README.md file:

> Please note .jsc files must run with the same Node.js version that was used to compile it (using **same architecture** of course).

**Comment by blackmiaool** [comment]
@OsamaAbbas  Yeah, but I can't get any info about "segmentation fault" at first time. So I just leave an issue here for reference.
