### ISSUE TITLE
Why is bytecode different in x86 and x64 architectures

### ISSUE THREAD

**Issue by Zhxhh** [bytenode/bytenode#143]
【This problem has nothing to do with this repo, it's just a technical consultation】
Bytecode should be platform-independent. Do you know why bytecode generation is different in different architectures?

**Comment by OsamaAbbas** [comment]
Because the v8 bytecode is an internal-purposed part that is not meant to be used the way we use it here. If you want a more detailed answer you should look into v8 source code (which is hard, really hard), or ask v8 people.
