### ISSUE TITLE
Still not very clear about electron + bytenode

### ISSUE THREAD

**Issue by soulkirito** [bytenode/bytenode#145]
Hi Sir, I had tried your example for Electron. By using 'npm start', the electron window pop out correctly with 'Hello World'. Then I tried to package it by using Electron-packager with the correct electron version (9.4.4), the exe did pop out an electron window but without "Hello World". Did I miss out something?
![npmstart](https://user-images.githubusercontent.com/66830063/126139370-ecc1ed73-a06f-4129-8f20-9f0a785b905d.JPG)
![electronpackager](https://user-images.githubusercontent.com/66830063/126139384-7c1a7260-81b8-4afb-8e30-bca92376c752.JPG)
![json](https://user-images.githubusercontent.com/66830063/126139395-86106c85-ac29-4cc1-bb1e-016612bed6fb.JPG)

**Comment by jjeff** [comment]
Try this:
https://github.com/spaceagetv/electron-bytenode-example

more background:
https://www.jjeff.com/blog/2021/4/27/creating-javascript-binaries-for-electron

**Comment by z3db0y** [comment]
Same here! I'm tryna build my app via `electron-builder` and compile the files. I have read about "same binary" stuff and "same version" but is it node or electron or both? I'M HELLA CONFUSED. Please give me an example with `electron-builder` and `bytenode`, not `electron-forge` as I have no experience with that. (I read Jeff's blog as well but I don't know how that is even supposed to work, all I have is an electron app with the builder).

I will try check Electron v17.4.0's node version in case it's different from my dev env version before complaining or sending any updates to this, but I think the formula is `node version of dev = node version of client app (bundled w/electron)`
As I said, I will try that and if it doesn't work I'll hit you up.

**Comment by OsamaAbbas** [comment]
First of all, I have zero experience with both `eletcron-forge` and `electron-builder`.

However, with regards to:
> I have read about "same binary" stuff and "same version" but is it node or electron or both? I'M HELLA CONFUSED.

This is a simple question. If your `.jsc` files will be run by electron, then the same electron binary that generates those `.jsc` file must be used in production. If your `.jsc` files with be run by node (as if your architecture includes an express server that runs in the background), then the same node that was used to compile your files must be used in production.

In most electron apps you will not use node at all. All your `.js` and `.jsc` files will be run inside electron. That is why bytenode cli uses electron internally to compile your code with the flag `-e` or `--electron`. Bytenode will use the locally installed version of electron. So, if `electron-builder` can bundle your app using the same locally installed version of electron, I believe it's easy to figure out how to setup your build routine. (again, I have no experience with all electron stuff! Sorry!).

**Comment by z3db0y** [comment]
Hmm, I'm not sure what binary electron-builder uses. But one thing I'm sure of is that I tried to run the compile with `npx electron deploy` (deploy.js having `bytenode.compileFile()` in it) and I still get the `Incompatible or invalid cached data` error after build

**Comment by OsamaAbbas** [comment]
If you can make a simple reproducible example (in another issue), I will look into it. But it has to be a complete example that can be run using a simple `npm install && npm start`.

**Comment by z3db0y** [comment]
Alright

**Comment by z3db0y** [comment]
I will ask in the electron discord in case anyone knows the solution

**Comment by soulkirito** [comment]
Use electron-forge instead of builder
