### ISSUE TITLE
JSC files not running

### ISSUE THREAD

**Issue by nehanegi220682** [bytenode/bytenode#146]
I have compiled my .js files to .jsc files. And the entry point is a file named app.jsc, but while running it throws a error saying that this format is not understood and you should have a loader. I dont know which loader do we need to configure for .jsc files?

ERROR in ./src/app.jsc 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

**Comment by OsamaAbbas** [comment]
`bytenode` must be required before any `.jsc` files. So, you have two options:

1. Use `bytenode` cli to run your `./src/app.jsc`. i.e. `bytenode ./src/app.jsc`.

2. Create another file, `launcher.js`, and require both `bytenode` and `./src/app.jsc` inside it.
```Javascript
require('bytenode');
require('./src/app.jsc');
```
