### ISSUE TITLE
source maps

### ISSUE THREAD

**Issue by piranna** [bytenode/bytenode#151]
Since now Node.js supports source maps when outputting errors, does it makes sense to generate them for `.jsc` files? I know main reason to use `bytenode` is to hide source code when distributed, but it can be useful to have them in case you need to debug a compiled file.

**Comment by piranna** [comment]
Any update on this? Any clue how can it be implemented? I think so far source maps are not publicly provided, we are safe...

**Comment by jjeff** [comment]
Duplicate of https://github.com/bytenode/bytenode/issues/219
