### ISSUE TITLE
Passing instances of ElementHandle to page.evaluate() in puppeteer workaround

### ISSUE THREAD

**Issue by abowcut** [bytenode/bytenode#155]
Hi there,

In general the issue with puppeteer's page.evaluate() and bytenode has been answered in previous issues.
However the example below remains unsolved from what I can tell.

You are allowed to pass instances of ElementHandle into page.evaluate functions with puppeteer, however with the two workarounds that have been described to use bytenode with page.evaluate (separate file for those functions/passing a string to page.evaluate) I can't find a way to pass instances of ElementHandle's into page.evaluate() function calls while still compiling to usable bytenode.

So in general, is there a way to get the below sample code to work with bytenode?

```
const bodyHandle = await page.$('body');
const html = await page.evaluate(body => body.innerHTML, bodyHandle);
```

I very much appreciate your effort and consideration.

**Comment by OsamaAbbas** [comment]
I will look into it tonight (hopefully). However, I believe this limitation is inside v8 itself, so it is nothing we can fix in Bytenode. Wherever there is a change in the context, or wherever the code will have to leave one instance of v8 to another instance (like from your code which is running inside node's v8, to the chromium's v8), the plain source code is needed. So, in principle, Bytenode will break.

I will look into it again to see if there is something we can do with it.

**Comment by abowcut** [comment]
Thanks for getting back so quickly.
I did find one way to workaround this for now, although I'm not sure if it will work for every scenario, but for my cases it seems to be working.

Note that this will not work in strict mode, and is janky to say the least.


```
const bodyHandle = await page.$('body');
eval("let tempFunc = async () => { let tempN = await page.evaluate((bodyHandle) => bodyHandle.innerHTML, bodyHandle); return tempN; }; var tempHTMLNode = tempFunc();");
const html = tempHTMLNode;
```

**Comment by OsamaAbbas** [comment]
I could finally look into this issue. I apologize for the terrible late response.

As we were expecting, any arguments that you pass to `page.evaluate()` function would survive if the `pageFunction` was sent as a string, see [ExecutionContext.ts#L199-L233](https://github.com/puppeteer/puppeteer/blob/8e45a1c882207cc36e87be2a917b661eb841c4bf/src/common/ExecutionContext.ts#L199-L233). So, you can't in principle use my previously suggested workaround.

So, that leaves us either with your workaround, or using `new Function` syntax. Here is my suggestion:

```Javascript
// file: index.js
'use strict';

const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    headless: false
  });
  const page = (await browser.pages())[0];
  await page.goto('https://google.com/ncr');
  const titleHandle = await page.$('title'); // selector for «Google offered in: ...» element
  const html = await page.evaluate(new Function('titleHandle', 'return titleHandle.innerText'), titleHandle);
  console.log(html);

  // await browser.close();
})();
```

Run `node index.js` and you will get: `Google`. Now, compile the file using `bytenode index.js -c` and run `bytenode index.jsc`. You should get the same message.

Note that `(body) => body.innerHTML` syntax will be translated to `new Function('body', 'return body.innerHTML')` in your example.

This solution works well with `'use strict;'`, which is a plus.

Let me know if you have any further questions.
