### ISSUE TITLE
Is it possible to make a .JSC file into a Windows executable?

### ISSUE THREAD

**Issue by KappasDEV** [bytenode/bytenode#156]
Could I possibly make a .jsc file and a .js file into a .exe or would I have to compile them both as .js files into a .jsc, then make them a .exe somehow?

**Comment by OsamaAbbas** [comment]
This would be tricky to achieve. You will have to use other tools that compiles node.js into exe. Then you would somehow use that exe as if it was node executable to compile your .js files to .jsc. Finally, you will have to recompile again to include your .jsc files.

For your use case, it's better to use `pkg`. I believe they have a built-in feature that is very similar to bytenode. I can't remember what it is called, but I remember looking into their source code and they were compiling plain js to v8 bytecode as well.
