### ISSUE TITLE
Add workaround for `Function.toString()` to docs

### ISSUE THREAD

**Issue by saucesteals** [bytenode/bytenode#163]
Lots of libraries rely on `Function.toString()` to function, so I think it's important to provide some sort of "hacky" solution to be able to use bytenode with the lib.

Ref: https://github.com/bytenode/bytenode/issues/93
Not only can you not use functions with puppeteer, but puppeteer now wraps all the string options (ex. `waitForSelector("selector")`) in a function, then calls `.toString()` on the wrapped function (or one that you've provided) before sending it to the browser

Ref: https://github.com/bytenode/bytenode/issues/34#issuecomment-807982226
Framework uses `Function.toString()` to check if `Function` is a class

As mentioned in https://github.com/bytenode/bytenode/issues/93#issuecomment-753661616 , a workaround could be just importing the function from a plain `.js` file, and while this will work, it may be a little unnecessary and annoying at times

A simple fix that I'd like to propose to get added to the documentation (or at least a reference to this issue) is the ability to override `.toString()` after bytenode breaks it

For example, to make a quick puppeteer fix:
```ts
const makeUnsafeFunction = (fnString) => {
    const fn = new Function(fnString);
    fn.toString = () => fnString;
    return fn
}

const unsafeWaitForSelector = (selector, opts) => {
    return page.waitForSelector(makeUnsafeFunction(`() => document.querySelector("${selector}")`), opts);
}

await unsafeWaitForSelector("#selector")
```

Or a fix for checking if a `Function` is a class:
```ts
class YourClass {}

YourClass.toString = () => "class YourClass"
```

This is in hopes to save people's time figuring out a good solution (because I know it would've saved mine 😅)

**Comment by OsamaAbbas** [comment]
I like the idea. Thank you for your contribution. I will add it to the README file later.

**Comment by OsamaAbbas** [comment]
Another suggestion that occured to me based on your idea: we may make bytenode extend the `Function.prototype` to add a method like `.preserveSourceCode()`. I have a general idea now of what is should look like and do, but I will implement it later.

The end goal is to make your examples like this:

```javascript
page.waitForSelector((() => document.querySelector("${selector}")).preserveSourceCode(), opts);
```

and

```javascript
class YourClass {}

YourClass.preserveSourceCode();
```

**Comment by saucesteals** [comment]
Definitely interesting but my guess is that there isn't gonna be a simple way to approach this and would have to do actual ast parsing - and at that point, it may as well just be comments on top of function declarations that preserve the source code since that seems to be what a lot of people have mentioned in past issues

**Comment by OsamaAbbas** [comment]
You are probably correct. I wrote my previous comment half asleep!

**Comment by saucesteals** [comment]
I think it could be relatively easy though considering how easy it is to parse and walk the js ast tree with modern packages
Purely a guess so correct me if I'm wrong but if the cached code just relies on some offset/position from the source that it tries to lookup when calling `Function.prototype.toString`, it should be relatively easy to just move the function (or even just the necessary parts of it) to the position in the dummy code that v8 would look into

And to be honest, since this feature is ever so rarely actually needed, you could just get away with two comments, one that marks the start of the source that you want to be preserved and one at the end. Do some simple regex matching or even pure js splitting and move those parts to the dummy code

**Comment by OsamaAbbas** [comment]
I added your workaround in the README file. Thank you.

**Comment by zhangriyueming** [comment]
> I think it could be relatively easy though considering how easy it is to parse and walk the js ast tree with modern packages Purely a guess so correct me if I'm wrong but if the cached code just relies on some offset/position from the source that it tries to lookup when calling `Function.prototype.toString`, it should be relatively easy to just move the function (or even just the necessary parts of it) to the position in the dummy code that v8 would look into
> 
> And to be honest, since this feature is ever so rarely actually needed, you could just get away with two comments, one that marks the start of the source that you want to be preserved and one at the end. Do some simple regex matching or even pure js splitting and move those parts to the dummy code

Check [here](https://github.com/Nihiue/little-byte/commit/0dd266d576175995360e8a81a1de70853d22c0e0) already a solution.

**Comment by DanielHougaard** [comment]
Please add an actual implementation of toString(). This approach makes it harder and harder to maintain your codebase when you need to edit the code inside the string.

**Comment by zhouzhili** [comment]
Is the `preserveSourceCode ` method implemented?

**Comment by j4k0xb** [comment]
> I think it could be relatively easy though considering how easy it is to parse and walk the js ast tree with modern packages Purely a guess so correct me if I'm wrong but if the cached code just relies on some offset/position from the source that it tries to lookup when calling `Function.prototype.toString`, it should be relatively easy to just move the function (or even just the necessary parts of it) to the position in the dummy code that v8 would look into
> 
> And to be honest, since this feature is ever so rarely actually needed, you could just get away with two comments, one that marks the start of the source that you want to be preserved and one at the end. Do some simple regex matching or even pure js splitting and move those parts to the dummy code

Here are both working attempts:
- [AST replacement](https://github.com/bytenode/bytenode/compare/master...j4k0xb:bytenode:preserve-function-source-ast)
- [Regex + Dummy code](https://github.com/bytenode/bytenode/compare/master...j4k0xb:bytenode:preserve-function-source)

With the AST it's easier to add a `.toString` property directly instead of dealing with offsets or modifying the cached data buffer
