### ISSUE TITLE
Invalid or incompatible cached data (cachedDataRejected)

### ISSUE THREAD

**Issue by SDAdham** [bytenode/bytenode#164]
Hello Osama,

I have the following problem below:
```
Error: Invalid or incompatible cached data (cachedDataRejected)
    at Object.Module._extensions.<computed> [as .jsc] (/home/<user>/nodevenv/node_modules/bytenode/lib/index.js:270:11)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/<user>/nodevenv/<process-path>/main.loader.js:3:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
```

I have seen https://github.com/bytenode/bytenode/issues/63 but I'm not sure if it's the same use-case as I do have here.

Here is what happened:

- I did initial CD deployment, it worked fine
- improved some of the code (worked on other things)
- did another push, CD deployment, it worked fine
- improved some of the code (worked on other things)
- Repeated the same process above for about 5-10 times
- At once (I didn't check the deployed environment after few commits so... I definitely need to guess which commit is the problem), I am getting that error, I am trying to figure it out if it's a deployment issue or something in my code.

In deployment, I stop the environment >> delete the old files >> reupload the new files >> start off the environment

I am running NestJS and unfortunately, I cannot upload a minimal reproduction for this issue nor that I can upload my project.

But may I please ask Osama, what could be the possible issues that can have this to happen?

You mentioned:
> I did as promised. However, there are many moving parts here (electron, vue, the whole build system, your own implementation of bytenode protection.. etc). It will take some time to pin where the issue lie exactly.
> 
> `cachedDataRejected` is always because the runtime executable differs from the executable that was used to generate the `.jsc` file. Also, any JavaScript code that will be run as a «browser javascript» (which is the case with Vue) cannot be compiled by bytenode. Bytenode only deals with «Node.js javascript». Your problem might be here (still not sure because I have not finished reading your code).
> 
> If you want to protect your «browser javascript» code, try using NW.js instead of Electron. They have a tool called `nwjc` that does just that.

Can you please explain more about this "`cachedDataRejected` is always because the runtime executable differs from the executable that was used to generate the `.jsc` file."?

Much appreciated.

**Comment by OsamaAbbas** [comment]
What are the versions of Node and bytenode in your project?

**Comment by SDAdham** [comment]
Yes, I made sure that both are the same and it's working, many thanks. I kinda figured from your statement:
> cachedDataRejected is always because the runtime executable differs from the executable that was used to generate the .jsc file. 

Many thanks Osama, you are awesome! :)

**Comment by janafsal** [comment]
how did you solve the issues, please explain as i have issue with 32 bit installer and for 64 bit it works

**Comment by SDAdham** [comment]
@janafsal , that can be because you are using 64 bit when building your project. Try 32 bit OS and see if it works.

**Comment by OsamaAbbas** [comment]
> how did you solve the issues, please explain as i have issue with 32 bit installer and for 64 bit it works

You can not cross-compile using bytenode. You MUST use the same exact binaries to compile `.js` files to `.jsc` files. The "same exact" means the SAME EXACT. The same exact binary that will be shipped to the user MUST be used to generate the `.jsc` files. (If I understand your issue correctly)

**Comment by janafsal** [comment]
> @janafsal , that can be because you are using 64 bit when building your project. Try 32 bit OS and see if it works. I had to adjust my pipelines for different platforms.

I am using electron forge to make installers from a 64 bit mechine, both installer(32 and 64) works fine without using JSC file, but with jsc file only 64 bit works as you said it may be because i make from a 64 bit mechine

**Comment by janafsal** [comment]
> > how did you solve the issues, please explain as i have issue with 32 bit installer and for 64 bit it works
> 
> You can not cross-compile using bytenode. You MUST use the same exact binaries to compile `.js` files to `.jsc` files. The "same exact" means the SAME EXACT. The same exact binary that will be shipped to the user MUST be used to generate the `.jsc` files in the first place. (If I understand your issue correctly)

Is there any alternative way to build 32 bit installer from a 64 bit mechine using bytenode

**Comment by OsamaAbbas** [comment]
> Is there any alternative way to build 32 bit installer from a 64 bit mechine using bytenode

If thr 64-bit machine can run the 32-bit electron, then it could be possible if you can tell the packager to use a custom electron copy to build the installer. It will be complicated though and there are many moving parts.

**Comment by OsamaAbbas** [comment]
It might be easier to install a 32-bit virtual machine from here https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ (choose one of the windows 7 machines, they are 32-bit) and build your app there.

**Comment by janafsal** [comment]
> It might be easier to install a 32-bit virtual machine from here https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ (choose one of the windows 7 machines, they are 32-bit) and build your app there.

This will be a cool idea, thanks bro… will try this one…
