### ISSUE TITLE
TypeError: object is not a constructor

### ISSUE THREAD

**Issue by AwesomeSam9523** [bytenode/bytenode#166]
![image](https://user-images.githubusercontent.com/76945339/142758118-0b98bd0a-7631-4113-a0fe-17cea11af806.png)

I get that after i pack my electron app and running the exe. Any clue whats wrong?

My main.js:
```js
require('bytenode');
require('./main.jsc');
```

How i use bytenode:
```js
const bytenode = require('bytenode');
..
const modifiedFile = await bytenode.compileFile({
    filename: './main.js'
});
```

**Comment by AwesomeSam9523** [comment]
I also tried
```js
const bytenode = require('bytenode');
..
const modifiedFile = await bytenode.compileFile({
    filename: './main.js',
    electron: true
});
```
Gives same error.

**Comment by AwesomeSam9523** [comment]
@OsamaAbbas hey just binging it into your notice

**Comment by OsamaAbbas** [comment]
The second example does not seem right to me. You only need ti specify `electron: true` if you are compiling from Node.

That being said, the issue is not apparent from your description. More code/information is needed.

**Comment by AwesomeSam9523** [comment]
> The second example does not seem right to me. You only need ti specify `electron: true` if you are compiling from Node.
> 
> That being said, the issue is not apparent from your description. More code/information is needed.

@OsamaAbbas The issue was importing files with a class. After moving them to my main.js file, the above issue has gone. But that being said, it gives a new error: 
![image](https://user-images.githubusercontent.com/76945339/142822095-91a5ff0a-f6b1-4811-a39c-f8abcf7f2a80.png)

I have `nodeIntergration` set to `true` in my BrowserWindow. But looks like the issue happens in `main.js`, where the code is:
```js
require('bytenode'); require('./main.jsc');
```

**Comment by OsamaAbbas** [comment]
Can you create a minimal complete example that produce the errors?

**Comment by AwesomeSam9523** [comment]
Sure. A pretty simple one:

`testclass.js`
```js
class Test {
    constructor(a, b) {
        this.a = a;
        this.b = b;
    }

    print() {
        console.log(this.a, this.b);
    }
}

module.exports = Test
```

`main.js`
```js
const Test = require('./testclass');

a = new Test(1, 2);
a.print();
```

Compiling:
```shell
bytenode -c -e main.js
bytenode -c -e testclass.js
```

New `main.js`:
```js
require('bytenode');
require('./main.jsc');
```

New `testclass.js`:
```js
require('bytenode');
require('./testclass.jsc');
```

Traceback:
```js
App threw an error during load
TypeError: object is not a constructor
    at Object.<anonymous> (evalmachine.<anonymous>:1:107)
    at Object.Module._extensions.<computed> [as .jsc] (F:\Samaksh\kpd\node_modules\bytenode\lib\index.js:305:26)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (F:\Samaksh\kpd\src\main.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
```

**Comment by AwesomeSam9523** [comment]
@OsamaAbbas could you reproduce it?

**Comment by OsamaAbbas** [comment]
I will look into it tonight and get back to you.

**Comment by OsamaAbbas** [comment]
The issue lies in your new `testclass.js` file. You have to export your class again:

```JavaScript
require('bytenode');
module.exports = require('./testclass.jsc');
```

Or, you can use `.jsc` directly from your "old" `main.js`, i.e. change it to use `testclass.jsc` before compiling it:

```JavaScript
const Test = require('./testclass.jsc');

a = new Test(1, 2);
a.print();
```

Or, if you deleted the plain `.js` files, the `require` function will automatically use the `.jsc` files, given that you have required `bytenode` as you've already done in your first line.
