### ISSUE TITLE
Change or remove extension while loading

### ISSUE THREAD

**Issue by leopucci** [bytenode/bytenode#168]
Hi. Thanks for your nice work!
I was wondering if I could change the extension, because it shows on process explorer my code running 
with the package bytenode and the extendion. 
I prefer to leave curious people unaware of details, and I was wondering if this could be possible.
it is possible to use fork without loading a .jsc file?
Thanks

**Comment by OsamaAbbas** [comment]
The upcoming major version (v2) will have this feature.

If you can't or don't want to wait, you can change the extension in ./lib/index.js#Line16 to whatever you prefer.

**Comment by leopucci** [comment]
Thank you @OsamaAbbas
