### ISSUE TITLE
require(...) is not a function

### ISSUE THREAD

**Issue by FAXES** [bytenode/bytenode#170]
Hello, when using bytenode. Compiling seems to be fully fine. However, when I use the `require()` function for Node.Js it returns;

```
require(`./updatemanager.jsc`)(app, connection, bot, itemVersion, faxstore);
                                  ^
TypeError: require(...) is not a function
```

The `updatemanager.jsc` file is a bunch of SQL queries. But it pretty much looks like
```js
const config = require('../config.json');
const fs = require("fs");
const axios = require('axios');
module.exports = async function(app, connection, bot, itemVersion, faxstore) {
    // SQL checks
    connection.ping(function (err) {
        if(err) {
            console.log(`\x1b[31mSQL connection failed. Ensure the login details are correct.\x1b[0m`);
            process.exit();
        }
    });
}
```

It is called via
```js
require('./updatemanager.jsc')(app, connection, bot, paypal, stripe, sgMail, faxstore);
```

Wondering what could case this issue and if there's any resolution.

**Comment by FAXES** [comment]
Turned out to be a syntax error inside the update manager file.

**Comment by OsamaAbbas** [comment]
Other potential reasons for this kind of error is compiling directly, without `compileAsModule: true` parameter.
