### ISSUE TITLE
require(...) is not defined

### ISSUE THREAD

**Issue by Itz-Hyperz** [bytenode/bytenode#173]
NodeJS Version: 16.13.1

Code before Bytenode
```js
const Discord = require('discord.js')
const client = new Discord.Client({
    intents: ['GUILDS', 'GUILD_MESSAGES', "GUILD_MESSAGE_REACTIONS", "DIRECT_MESSAGES", "GUILD_MEMBERS", "GUILD_BANS", "GUILD_INTEGRATIONS", "GUILD_WEBHOOKS", "GUILD_INVITES", "GUILD_VOICE_STATES", "GUILD_PRESENCES", "GUILD_MESSAGE_TYPING", "DIRECT_MESSAGE_REACTIONS", "DIRECT_MESSAGE_TYPING"],
    partials: ["CHANNEL", "MESSAGE", "REACTIONS"],
    allowedMentions: { parse: ['users', 'roles', 'everyone'], repliedUser: true }
});

client.on('ready', function() {
    console.log(`Logged in as ${client.user.tag}!`);
});

client.on('message', function(message) {
    if(message.content.startsWith(`!ping`)) {
        message.channel.send({ content: "Pong!" })
    }
});

client.login('TOKEN_HERE')
```

after running compileFile() with Bytenode and then running that compiled file, it throws this error:
![example](https://cdn.hyperz.net/main/QLi8V7.png)

any ideas?

because this is how I run the file inside of my actual code:
```js
const bytenode = require('bytenode');
bytenode.runBytecodeFile('./compiled.jsc');
```

**Comment by Itz-Hyperz** [comment]
For reference I am compiling test.js INTO test1.jsc like this:
```js
let compiledFilename = bytenode.compileFile({
  filename: './test.js',
  output: './test1.jsc'
});
```

**Comment by OsamaAbbas** [comment]
There is some confusion on the way you use bytenode.

For example, in your first example:

```JavaScript
const bytenode = require('bytenode');
bytenode.runBytecodeFile('./compiled.jsc');
```

Here, you should use `require('./compiled.jsc')` directly, not `bytenode.runBytecodeFile`.

Also, in your second example:
```JavaScript
const { Client } = require('discord.js');
require('./test1.jsc')(Client)
```
You can't require any `.jsc` files without requiring `require('bytenode')` first.

If you can create a simple (yet complete) example for your use case, I will help you figure out what went wrong.

**Comment by Itz-Hyperz** [comment]
ohhhhh, you have to require bytenode even when you aren't calling it anywhere?

**Comment by Itz-Hyperz** [comment]
ignore the first example now though

**Comment by OsamaAbbas** [comment]
> ohhhhh, you have to require bytenode even when you aren't calling it anywhere?

Yes, absolutely. If you want to require `.jsc` files, you MUST tell the `require` function how to deal with that extension. bytenode handles that for you (i.e., it registers this `.jsc` extension with node module system).

> so my code would have to look like this:
> 
> ```js
> require('bytenode');
> const { Client } = require('discord.js');
> require('./test1.jsc')(Client)
> ```
> 
> and that should work?

Theoretically, yes. However, if there is different contexts in play, things might need to be handled differently. If your code does not work, you have to provide a minimal reproducible example that shows normal code works while bytenode compiled code does not work.

**Comment by Itz-Hyperz** [comment]
Would you mind showing me where it registers the `.jsc` files in the bytenode module? I'd like to possibly add onto this.

**Comment by Itz-Hyperz** [comment]
didnt mean to close.

**Comment by Itz-Hyperz** [comment]
nevermind, thank you so much for the help!

**Comment by OsamaAbbas** [comment]
> Would you mind showing me where it registers the `.jsc` files in the bytenode module? I'd like to possibly add onto this.

Here: https://github.com/bytenode/bytenode/blob/3a42649a61f17773e654caaee863e2f9680ca6d7/lib/index.js#L250
