### ISSUE TITLE
check failed: stack_overflow()

### ISSUE THREAD

**Issue by FAXES** [bytenode/bytenode#174]
This is the error

```
#
# Fatal error in , line 0
# Check failed: stack_overflow().
#
#
#
#FailureMessage Object: 0x7ffdc48c3860
 1: 0xb6d391  [FaxSto]
 2: 0x1bf6a04 V8_Fatal(char const*, ...) [FaxSto]
 3: 0x113ae31 v8::internal::Parser::DoParseFunction(v8::internal::Isolate*, v8::internal::ParseInfo*, int, int, int, v8::internal::AstRawString const*) [FaxSto]
 4: 0x113b2dc v8::internal::Parser::ParseFunction(v8::internal::Isolate*, v8::internal::ParseInfo*, v8::internal::Handle<v8::internal::SharedFunctionInfo>) [FaxSto]
 5: 0x1144104 v8::internal::parsing::ParseFunction(v8::internal::ParseInfo*, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Isolate*, v8::internal::parsing::ReportStatisticsMode) [FaxSto]
 6: 0x11444fd v8::internal::parsing::ParseAny(v8::internal::ParseInfo*, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Isolate*, v8::internal::parsing::ReportStatisticsMode) [FaxSto]
 7: 0xe421e4 v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::MaybeHandle<v8::internal::Object>) [FaxSto]
 8: 0x11fa7ef v8::internal::Runtime::GetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, bool*) [FaxSto]
 9: 0x11fd98f v8::internal::Runtime_GetProperty(int, unsigned long*, v8::internal::Isolate*) [FaxSto]
10: 0x15e7cf9  [FaxSto]
Trace/breakpoint trap (core dumped)
```

I've read the readme and it mentions arrow functions to be a possible cause. However, only some users using my application experience this issue whereas others are completely fine.

So this made me think if it's a compiling issue or if it's another possible issue.

Their OS (Ubuntu 20.04 LTS) and node version (16.13.2) are the same as others who are also using the application.

**Comment by FAXES** [comment]
Some insight to specific causes of this error would be helpful ❤️

**Comment by OsamaAbbas** [comment]
If both groups have the same arch, then I cannot think of other possiblr causes other than arrow functions; I don't know (without seeing your code) why only some of your users experience the error though.

Get rid of arrow functions and see what will you got.

**Comment by FAXES** [comment]
> If both groups have the same arch, then I cannot think of other possiblr causes other than arrow functions; I don't know (without seeing your code) why only some of your users experience the error though.
> 
> Get rid of arrow functions and see what will you got.

Do you recommend just removing *all* arrow functions everywhere?

**Comment by OsamaAbbas** [comment]
Yes, because you never know when will v8 do its thing and check for their source code, which will be missing in your jsc files, hence the error.

**Comment by FAXES** [comment]
Currently working with the user to narrow down the issue. I've replaced every single arrow function in the whole application (over 800 of them).

Now narrow it down to content in a particular file which is only throwing the error when that file is loaded

**Comment by FAXES** [comment]
Research is showing it came down to a connection query where the UPDATE TABLE statement failed as the table didn't exist. Odd that instead of throwing its error, it caused this error response.

I'll test with the other users and report back if this is consistent.

**Comment by eduardokreve** [comment]
The same error is happening to me. Was the issue resolved by removing the arrow functions?

**Comment by OsamaAbbas** [comment]
Try and see if it solve your problem. The error is not specific to one cause, so we don't know unless we know your exact code.

Arrow functions cause that sort if error, so removing them might help you.

**Comment by FAXES** [comment]
Removing the arrow functions from that query that failed above fixed it.
