### ISSUE TITLE
[Question]: Payload size limit?

### ISSUE THREAD

**Issue by overflowz** [bytenode/bytenode#178]
First of all, great project and great work!

Now the question, of curiosity, if the payload (e.g., bundled script) size is greater than 0xFFFFFFFF bytes, would bytenode still work? I'm asking because `kPayloadLengthOffset` is just uint32.

Thank you.

**Comment by OsamaAbbas** [comment]
This question crossed my mind before. I don't believe this limitation applies exclusively with bytenode, because the same logic and limitation still will be used with any script that v8 deals with (i.e. all javascript files). I think I tried before to generate a huge javascript file and run it with and without bytenode, but I don't remember the results though :) . I might try the same experiment again and get back to this issue.

Thanks for your interest and your kind words.

**Comment by OsamaAbbas** [comment]
I vaguely remember that I had to use repetitions in order to reach that huge limit (~4.2 Gb), however, v8 was smart enough to remove that repeated parts in the code before compiling it. So the compiled version was much smaller.

Will try again definitely. That's an interesting question.

**Comment by overflowz** [comment]
Yea, repetitions will be removed due to the optimizations

**Comment by OsamaAbbas** [comment]
Well, it was a painful experiment :), but at least we found a definite answer:

```
$ time node HUGE.js 
node:fs:419
      throw new ERR_FS_FILE_TOO_LARGE(size);
      ^

RangeError [ERR_FS_FILE_TOO_LARGE]: File size (4543783398) is greater than 2 GB
```

The `HUGE.js` file was 4.5 GB.

So the conclusion is that neither the Node.js limit (2 Gb) nor the v8 limit (0xFFFFFFFF) will pose a problem for bytenode.

**Comment by OsamaAbbas** [comment]
I reduced the file to 1.9 Gb, but it still throws an error:

```
$ time node HUGE.js 
node:buffer:594
    slice: (buf, start, end) => buf.utf8Slice(start, end),
                                    ^

Error: Cannot create a string longer than 0x1fffffe8 characters
```

So, as you can see, Node itself has its limits before hitting any limits in the v8 C++ code. Anyways, for all practical purposes, you will not reach these limits, and even if you managed to reach them, bytenode will not be your issue.

An interesting fact is that `.jsc` files outperform plain `.js` files by a large margin when the files are huge (several hundreds megabytes). For example (`huge-1.js` was 325 Mb):

```
$  time node huge-1.js 
output: c4ca4238a0b923820dcc509a...

real	1m11.527s
user	0m33.258s
sys	0m38.229s

$ time bytenode -c huge-1.js 

real	1m13.891s
user	0m32.210s
sys	0m41.429s

$ time bytenode huge-1.jsc 
output: c4ca4238a0b923820dcc509a...

real	0m1.106s
user	0m0.564s
sys	0m0.548s
```

1:11.527 vs 0:1.106. That's a huge performance gain.

**Comment by overflowz** [comment]
Thank you for the research! Yeah, the performance is just too much haha, guess it does not need to produce bytecodes (including optimizations, etc) anymore and that could be the thing ;p
