### ISSUE TITLE
Folder with .js in the name breaks compilation

### ISSUE THREAD

**Issue by WhoAteDaCake** [bytenode/bytenode#184]
I've tried to run `bytenode --compile ./**/*.js` against node_modules, however, it failed with 

> Error: Cannot find file '/home/toshiba/open-source/node-hello/node_modules/ipaddr.js'

I've ran `npm i express` to get these packages

**Comment by ngohuytrieu** [comment]
You should've not compiled the node_modules folder

**Comment by OsamaAbbas** [comment]
> I've tried to run `bytenode --compile ./**/*.js` against node_modules, however, it failed with
> 
> > Error: Cannot find file '/home/toshiba/open-source/node-hello/node_modules/ipaddr.js'
> 
> I've ran `npm i express` to get these packages

I will fix it in an upcomming update. However, you should not compile `node_modules` files. I bet that compiling them will break your project 90% of the time.

**Comment by WhoAteDaCake** [comment]
Thank you for your help, I had the wrong assumption that I could compile down all of the node_modules folders in order to reduce the size of node_modules, but it seems that it's not a usecase for this library
