### ISSUE TITLE
Compiling for Windows from M1 Mac machine with Electron 18 crashing

### ISSUE THREAD

**Issue by felipe-linares** [bytenode/bytenode#185]
Currently upgrading to Electron 18 for our application and our CI/CD setup is using an M1 mac machine for cross-compilation.
It seems that when compiling Bytenode for electron on the M1 machine, it causes a native crash on Electron.

After a lot of testing, it seems the root cause is bytenode. When I copy the `main.jsc` file compiled on Windows to the mac machine and use electron-builder on THAT, it works just fine. It is PURELY the `main.jsc` file created on the mac machine (have tried several mac machines including my personal M1 macbook pro).

Here is the stack trace of the crash using visual studio from the crash dump (application name excluded).
![image](https://user-images.githubusercontent.com/22437981/171198280-addc2519-37d7-4531-a999-929bfe34e965.png)

NOTE: This worked perfectly on Electron v12 - has something changed since then that I am unaware of?

Our basic workflow uses webpack (v5 which is why we have the bytenode script separate instead of using the bytenode plugin) to bundle the main.js file and then runs it through the script below to load the application:

```
const project = process.argv[2];
const buildPath = path.resolve('..', `${project}/build`);
const dummyCode =
  "const Buffer = require('buffer').Buffer; const v8 = require('v8'); v8.setFlagsFromString('--no-lazy'); require('bytenode'); module.exports = require('./main.jsc');";

const preparedCode = babel.transformSync(
  fs.readFileSync(`${buildPath}/main/main.js`, 'utf8'),
  {
    plugins: ['@babel/plugin-transform-arrow-functions'],
    babelrc: false,
    minified: true,
  },
).code;

fs.writeFileSync(`${buildPath}/main/main.js`, preparedCode);

bytenode.compileFile({
  filename: `${buildPath}/main/main.js`,
  compileAsModule: true,
});

fs.writeFileSync(
  `${buildPath}/main/main.js`,
  dummyCode,
);

**Comment by OsamaAbbas** [comment]
> NOTE: This worked perfectly on Electron v12 - has something changed since then that I am unaware of?

I did not know that we can do that to be honest. But, if you really was able to cross compile for windows on mac with Electron 12, then the issue does not seem to be in bytenode.

But again, I really did not know that this is possible. If you asked me I would have said that it is impossible currently, because v8 bytecode (which bytenode uses) depends on the arch and the platform (and the v8's version and node's).

**Comment by felipe-linares** [comment]
I think something in the underlying node version in Electron 12 made it possible, or maybe something in our CI/CD setup (it's a bit complicated so I'm not sure).

I finally got it to work by forcing node modules to install on the M1 machine with `npm_config_arch` & `npm_config_target_arch` set to `x64` for the yarn install step.

This forces the electron version installed to be the x64 version and when we run bytenode it compiles using electron x64 as the runtime instead of arm64.

Thanks anyway for the help @OsamaAbbas 

Just wanted to update this in case anyone runs into similar issues in the future
