### ISSUE TITLE
Syntax error when using Electron to compile

### ISSUE THREAD

**Issue by sbhehe233** [bytenode/bytenode#187]
Hi there,

When I tried use Electron to compile (with the cmd `bytenode -e -c ./dist/**/*.js`) I ran into the errors below:

```
Error:  /builds/node_modules/electron/dist/electron.exe: 3: Syntax error: ";" unexpected
Error:  /builds/node_modules/electron/dist/electron.exe: 3: Syntax error: ";" unexpected
```

Here's my system specs:

```
Pipeline system image: electronuserland/builder:16-wine 
NodeJS: v16.14.2
electron-builder  version=23.0.3 os=5.10.117
platform=win32 arch=x64 electron=19.0.4
```

The same JS files can be compiled w/o problem w/o the `-e` switch BTW...

Here's a sample of the offending scripts:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const app_1 = require("./app");
const app_module_1 = require("./app.module");
const expressApp = (0, app_1.default)(app_module_1.ApplicationModule);
exports.default = expressApp;
//# sourceMappingURL=index.js.map
```

Any ideas? Thanks!

**Comment by OsamaAbbas** [comment]
Sorry for the late response.

What is your operating system? Are you trying to compile for windows on a linux machine?

Can you provide a minimal reproducible example?

**Comment by sbhehe233** [comment]
```
What is your operating system? Are you trying to compile for windows on a linux machine?
```

Yep this is happening in our pipelines running the [electronuserland/builder:16-wine-chrome](https://hub.docker.com/r/electronuserland/builder) image.

You may simply reproduce this by compiling any code within a container of the image above, with the win32 Electron executables:

```
npm i -g electron@^19.0.0 bytenote --platform=win32
bytenode -e -c *.js
```

Could compile succcessfully however if the deps were installed w/o specifying the platform - but that could lead to a `Invalid or incompatible cached data ` error when running the Electron executable that was produced ... guess that was caused by compiling  for Windows with Linux Electron?

Thanks!

**Comment by OsamaAbbas** [comment]
I don't think what you are trying to do is possible in principle. At least you can't run the Linux's version of Node and ask it to "compile" your `.js` files using the Windows's version of Electron (even by using Wine).

Maybe you want to try to run the whole logic through wine? I mean, including `npm.exe install bytenode electron` and `node.exe -r bytenode -e -c file.js`.

**Comment by sbhehe233** [comment]
Tks @OsamaAbbas and I was able to solve this! Turned out the v8 engine version bundled with Electron v19 was different than the one that comes with the native v16.14.2 (`10.2.154.4-electron.0` vs `9.4.146.24-node.20`) and hence the mismatch, so I just needed to strictly use Electron of the exact same arch & version to compile and pack - here's what I did if anyone's interested:

```
Pipeline system image: electronuserland/builder:16-wine-chrome
NodeJS: v16.14.2
electron-builder  version=23.0.3 os=5.10.117
platform=win32 arch=x64 electron=19.0.4
```

Pipeline commands:
```
npm i bytenode
npm i --platform=win32 --arch=x64 --verbose electron@19.0.0
bytenode -e -c *.js
electron-builder --win
```

Worked like a charm! ^_^
