### ISSUE TITLE
Invalid or incompatible cached data (cachedDataRejected)

### ISSUE THREAD

**Issue by mertushka** [bytenode/bytenode#189]
I have an Electron application packaged with electron-builder. I wanted to use Bytenode, but I guess I couldn't do exactly what I wanted to do.

How can I compile the code for electron using the Bytenode API, i don't want to use the CLI.

## Electron App

- main.js
```js
const { app } = require("electron");
const bytenode = require("bytenode");
bytenode.runBytecodeFile(`${app.getAppPath()}/index.jsc`);
```

## Bytenode API

- compiler.js
```js
files.forEach(file => {
bytenode.compileFile({
filename: path.join(__dirname, "../sources/buildFiles", file), // sources/buildFiles is including electron app's source files (like index.js, preload.js)
electron: true,
compileAsModule: false,
output: path.join(__dirname, "../builder/", file.replace(".js", ".jsc")), // builder is electron app folder dest
});
});
```

## Error
![n180s](https://user-images.githubusercontent.com/34413473/179365016-a2df02b4-cf99-4023-a6c3-57f5e470e3cc.png)

**Comment by OsamaAbbas** [comment]
How do you run this file `compiler.js`?

**Comment by mertushka** [comment]
> How do you run this file `compiler.js`?

As usual with NodeJS

**Comment by OsamaAbbas** [comment]
You cannot compile your `.js` files to `.jsc` using Node executable if you want them to be run through electron. They must be compiled using electron itself.

You will have to run your `compiler.js` with electron itself, with the `ELECTRON_RUN_AS_NODE` env variable set correctly.

In Windows, you will need to set it like this (using cmd.exe):

`set ELECTRON_RUN_AS_NODE=true`

Then:

`C:\path\to\electron.exe compiler.js`

Let me know if this solves your issue.

**Comment by wcldyx** [comment]
> You cannot compile your `.js` files to `.jsc` using Node executable if you want them to be run through electron. They must be compiled using electron itself.
> 
> You will have to run your `compiler.js` with electron itself, with the `ELECTRON_RUN_AS_NODE` env variable set correctly.
> 
> In Windows, you will need to set it like this (using cmd.exe):
> 
> `set ELECTRON_RUN_AS_NODE=true`
> 
> Then:
> 
> `C:\path\to\electron.exe compiler.js`
> 
> Let me know if this solves your issue.
I tried it, but still the error "Invalid or incompatible cached data"

**Comment by OsamaAbbas** [comment]
To get this clear, how did you compike to 32-bit? Using the 32-bit exe itself or using some kind of cross-compilation?

**Comment by wcldyx** [comment]
> To get this clear, how did you compile to 32-bit? Using the 32-bit exe itself or using some kind of cross-compilation?

Packaged as 32-bit using "electron-builder"

**Comment by OsamaAbbas** [comment]
Again, you CANNOT do that. You MUST use the SAME executable to compile the files AND to run your code.

What you have did is simply compiling using the 64-bit, then you asked electron-builder to take these files and bundle them with the 32-bit executable. Do you see the issue now?

Please pay attention, the SAME EXACT ELECTRON EXE MUST be used in both compiling AND running your end product.

**Comment by moeelbadri** [comment]
for anyone coming for this issue
bun add -d electron --arch=ia32
ucan install it in another project / folder so it wont affect ur current electron
copy the electron folder from the nodemodules
paste it in ur project and make sure to change the name to smth else e.g. electron-bits32
simply in defineConfig in electron vite config
process.env.ELECTRON_EXEC_PATH = './node_modules/electron-bits32/dist/electron.exe'
simply like that
bun run build && electron-builder --win --ia32 --dir
dont forget to set the arch ia32 for electron-builder too
good luck!
