### ISSUE TITLE
How does this effect the code execution speed?

### ISSUE THREAD

**Issue by dipakw** [bytenode/bytenode#192]
Hi,

I guess the code execution should be a bit faster with the bytecode. Would you guys please let me know whether the code execution speed will be faster or slower?

**Comment by ngohuytrieu** [comment]
So far I've tried it on my small project. The speed seems to have no big difference before and after encrypted.

**Comment by OsamaAbbas** [comment]
It is the same performance or even faster. But the difference is unnoticeable in almost all cases.
