### ISSUE TITLE
How to run my Electron TypeScript application?

### ISSUE THREAD

**Issue by colinrw** [bytenode/bytenode#194]
Hi everyone, I am trying to implement bytenode, but I am a bit stuck with making my application run with `.jsc` files. These are the steps that I took:
1. Converted my TS files to JS files;
2. Use the `bytenode --compile` command to convert all these JS files to JSC files;
3. Removed all the JS files;

Right now I've got all my files converted to JSC files, but I have no idea how to run my application with these JSC files. 
I've read that I had to add `require('./main.jsc');` to my files, but they all seem to give errors when I try to run the code the original code. 

Does anyone have an idea/walkthrough to run an Electron app with JSC converted files? Thank you 🙂
Operating system: macOS

**Comment by OsamaAbbas** [comment]
You have to `require('bytenode')` before running your `.jsc` files.

And, you have to use electron executable itself in compiling your code. You can not compile them using node amd run them using electron.

**Comment by colinrw** [comment]
@OsamaAbbas thank you for the fast answer! 
Do I have to add `require('bytenode')`+ the name of the `.jsc` file in every file that I compile to bytenode or is there a better way to do this?

**Comment by OsamaAbbas** [comment]
The line `require('bytenode')` should appear once in your app. All it does for you in this case is registering the jsc files to let node know how to run them. Once registered once in your app lifecycle, it will stay until the process is closed.

So basically, add this line at the very beginning of your app.

**Comment by colinrw** [comment]
@OsamaAbbas I've sent you an email 🙂
