### ISSUE TITLE
[feature] support es module.

### ISSUE THREAD

**Issue by radiorz** [bytenode/bytenode#196]
Es modules become more and more popular.
if possible please support es modules.

**Comment by OsamaAbbas** [comment]
I believe that most APIs that are needed to make bytenode work with es modules are still exprerimental. When they become stable I will consider the possibility of supporting them.

Also, in Node.js, there is really no point to favor es modules over commonjs modules. Quite the opposite in fact.

It is also much easier to transpile your code to commonjs. Most people use typescript and webpack anyways, so adding one extra step is managable.

**Comment by stefreak** [comment]
@OsamaAbbas Some time has passed, and the conditions have changed slightly:

- ES Module support is now stable https://nodejs.org/api/esm.html
- Now that ES modules are more widespread, some libraries opted to publishing only ESM versions. Sometimes these libraries use top-level await, which cannot be transpiled to CommonJS.
- This creates an incentive for application maintainers to switch to ESM, to keep dependencies up-to-date. We [recently did that at Garden](https://github.com/garden-io/garden/pull/5233).

Would you be open to reconsider supporting ES Modules in Bytenode?

**Comment by OsamaAbbas** [comment]
> @OsamaAbbas Some time has passed, and the conditions have changed slightly:
> 
> * ES Module support is now stable https://nodejs.org/api/esm.html
> * Now that ES modules are more widespread, some libraries opted to publishing only ESM versions. Sometimes these libraries use top-level await, which cannot be transpiled to CommonJS.
> * This creates an incentive for application maintainers to switch to ESM, to keep dependencies up-to-date. We [recently did that at Garden](https://github.com/garden-io/garden/pull/5233).
> 
> Would you be open to reconsider supporting ES Modules in Bytenode?

Check out my comment [here](https://github.com/bytenode/bytenode/issues/95#issuecomment-1751569431)

**Comment by guyedry1** [comment]
Hi @OsamaAbbas,
Hope you doing well.

Seems many libraries im using at least are ESM only. i got a project im pushing to users but im looking for a way to use bytenote before sending it to them to ensure the source code is secure.

any ideas?
thanks.
