### ISSUE TITLE
Not be able to use path.join

### ISSUE THREAD

**Issue by JNLei** [bytenode/bytenode#199]
After long time debugging, I found using `path.join` will cause the app to crash.
I also see the limitation has:
>  Any code depends on Function.prototype.toString function will break

Is this the root cause of not be able to use `path.join`?
If so, how come the app works fine on Windows but not on Mac. I keep getting `undefined is not a function` wherever I used `path.join` on Mac.

**Comment by OsamaAbbas** [comment]
`path.join` works and always worked with no issues. It has nothing to do with the `Function.prototype.toString` limitation.

If you can create a minimal example that shows your error on mac, I will check and try to figure it out.

**Comment by JNLei** [comment]
Here is the minimal example. I just clone the electron example, and upgrade to use electron 21.0.1.

[electron-hello-world.zip](https://github.com/bytenode/bytenode/files/10191074/electron-hello-world.zip)

When you run `rpm start`, everything goes fine, but after run `nom run build` and open the binary, the following error shows:
<img width="248" alt="Screen Shot 2022-12-08 at 8 44 37 PM" src="https://user-images.githubusercontent.com/16848622/206604235-93a9827b-42a9-4af8-a514-f6d91dab7050.png">

From the console log result, I can see the issue happens when `path.join` is called.

I'm using Mac OS Version 12.0 with M1, and I'm using Rosetta Terminal to build. 

Thanks!

**Comment by OsamaAbbas** [comment]
For some reason, `npm run build` throws this error on my machine:

```
osama@Mac-mini electron-hello-world % 
 npm run build

> electron-hello-world@0.0.1 build /Users/osama/Desktop/Dev/electron-hello-world
> electron-builder --x64

Error: Cannot find module 'fs/promises'
.
.
.
```

The electron example in bytenode repo is quite old. I think it's better to try the current official quick example from electron website.

I'm a bit busy currently, but I will try to put a minimal example using `electron-builder` to figure out the issue.

**Comment by JNLei** [comment]
Use Node v14+ to build should solve the issue @OsamaAbbas

**Comment by OsamaAbbas** [comment]
I updated my node.js version to v18 and I was able to build the example.

However, I could not produce your error. Your app works fine whether it's `npm run start` or `npm run build`.

I'm using macOS Monterey (version 12.6) too, the default terminal though, and with node v18.12.1.

**Comment by JNLei** [comment]
I was also able to build, I met the above error when I ran the binary that was built.

**Comment by OsamaAbbas** [comment]
Yeah, I was able to run the app that was built.

**Comment by JNLei** [comment]
I managed to have the M1 version built success. Still have some issues with the intel version, but it has nothing to do with bytenode. Thanks for your help! @OsamaAbbas .  Closing the issue.

**Comment by OsamaAbbas** [comment]
The only thing that I may mention is that you have to build your app for each platform separately. The binaries that were built for Intel won't work for M1 and vice versa.

Good luck with your project.
