### ISSUE TITLE
Use in electron  14 in   render

### ISSUE THREAD

**Issue by samantrader** [bytenode/bytenode#200]
HI  
if   I  can  use bytenode  in  render  section  of electron  app  without   use of  preload  js  file  with  just 
  nodeIntegration: true  ?

**Comment by OsamaAbbas** [comment]
Yes you can. However, this might not be the case in the future when electron removes `vm` module from the render process.

But currently, yes.

**Comment by samantrader** [comment]
thank you   and  another question 
if anyone  can   convert  binary code that generated  with bytecode  to   plain  javascript  ( original source )  ?

**Comment by OsamaAbbas** [comment]
It's not possible as of now. What is possible though is doing a reverse engineering for the binary, just like someone can reverse engineer a compiled c++ program.

So, it is possible to reverse engineer the compiled code to figure out its logic, but it's not possible to get your plain js code.

If you are worried that a customer or a competitor would re-create your work: don't worry. It is far easier to clone your app from the scratch than to reverse engineer it and trying to make sense of it.

However, if you want to hide something sensitive inside a compiled code: this is the wrong approach, even in C++.

Or, if someone is trying to create malicious code: security experts can reverse engineer that malicious app and know how it works and what is attacks.
