### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by 82318179** [bytenode/bytenode#201]
const abc = () => {
    console.log('我知道了')
  }
  mytest.eval(abc.toString())

After using code protection, the above codes report the following error
Uncaught SyntaxError: Invalid or unexpected token

fn.tostring()  is not work in code protection ,how to fix this error

**Comment by OsamaAbbas** [comment]
Bytenode works by removing your plain source code, so by definition it breaks the `Function.prototype.toString()` function.

This is mentioned in the README file.
