### ISSUE TITLE
Invalid or incompatible cached data (cachedDataRejected) - NodeJS to NodeJS Test

### ISSUE THREAD

**Issue by ganeshsacharya** [bytenode/bytenode#207]
Hello, 

On my actual project i intend to use bytenode to obfuscate my code(assume an important plugin for a project) so i can ship it when i do the integration in the client project.

Apparently after trying multiple things i finally kind of realised the below:
If you convert .js to .jsc using the common-js bytenode package in a specific node version, i could only use this in that specific node version and nothing else!

If i compile the .js file in Node version 16 and try to use it with Node Version 14, it throws the Invalid or incompatible cached data (cachedDataRejected) error. 

Is this correct? or is there a way around it?

To explain my setup better i have a small repo prepared: [REPO](https://github.com/khazaddoom/bytenode-test)

Please help me with some inputs here.

**Comment by OsamaAbbas** [comment]
This cannot be done. It's mentioned in the README file as well.

There is a way to ignore all v8 sanity checks and to run the `.jsc` files forcefully, but this will result in nasty c++ errors that crash your app.

**Comment by OsamaAbbas** [comment]
Also, avoid arrow functions (I saw some in your repo). They tend to cause problems whenever there is a context switch inside v8.

**Comment by ganeshsacharya** [comment]
Thanks a lot for Replying.
Can you point me to the exact section in the README.md file please? i think i missed it.

**Comment by OsamaAbbas** [comment]
The last paragraph before Acknowledgements section.

> Please note `.jsc` files must run with the same Node.js version that was used to compile it (using same architecture of course). Also, `.jsc` files are CPU-agnostic. However, you should run your tests before and after deployment, because V8 sanity checks include some checks related to CPU supported features, so this may cause errors in some rare cases.
