### ISSUE TITLE
开发含有native插件打包加密时，会有问题，检查过代码，怀疑是bytenode的问题

### ISSUE THREAD

**Issue by jincandev** [bytenode/bytenode#211]
问题描述： https://github.com/dusionlike/electron-builder-encryptor/issues/7#issue-1640581245

**Comment by OsamaAbbas** [comment]
I don't understand Chinese, sorry. Please try to use English.

From what I see in the error message, the issue is that your `.node` (which is native modules) is missing. This issue has nothing to do with bytenode.
