### ISSUE TITLE
toString issue clarification

### ISSUE THREAD

**Issue by srcastor** [bytenode/bytenode#225]
I have compiled a file in electron and it is working perfectly, however the file contains more than 30 mentions toString, it also has several calls to JSON.parse which from what I have read here, also seems to cause problems. In my particular case all the calls are working correctly.

I'm missing something for sure , can someone clarify what it's the bug with toString?

**Comment by OsamaAbbas** [comment]
The issue is only restricted to `Function.prototype.toString` function. So, you will only face a problem if you try to invoke `.toString()` from any function, because the compiled code will return an empty string instead of your code.

Invoking `.toString` on any other object is completely fine.
