### ISSUE TITLE
BIG problem: v1.5.4 CLI doesn't work on linux!

### ISSUE THREAD

**Issue by System233** [bytenode/bytenode#228]
In the latest 1.5.4 version, the [cli.js](
https://www.npmjs.com/package/bytenode/file/67b5f06b0fb3f124eed4c381c2515e315fb32637052f933954162a2ba703db15) file is injected with a CR newline character, which causes the interpreter command `#!/usr/bin/env node` to fail and the `bytenode` command to be completely unusable.

Before releasing a new version, please do not edit the source files in Notepad on the Windows platform.

![image](https://github.com/bytenode/bytenode/assets/20336040/11dbd672-d5a4-4aea-a734-c395daf820a5)

```shell
/app # vi /usr/local/bin/bytenode
/app # bytenode -v
': No such file or directory
/app #
```

**Comment by OsamaAbbas** [comment]
I haven't used Notepad in years. If your diagnosis is correct, it might be Git for Windows that injected those characters.

I will check and publish a fix now.

**Comment by System233** [comment]
> I cannot find any characters in file. Also, version works properly on my linux machine.`\r``cli.js``1.5.4`
> 
> ![image](https://private-user-images.githubusercontent.com/3346502/311653601-38a628fe-7bce-4439-9819-94ad4ae1a502.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTAwMTcsIm5iZiI6MTcxMDE0OTcxNywicGF0aCI6Ii8zMzQ2NTAyLzMxMTY1MzYwMS0zOGE2MjhmZS03YmNlLTQ0MzktOTgxOS05NGFkNGFlMWE1MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTFUMDkzNTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzJmNjliMDc1ZDEzMmQxOWQwMDEyNTdmYTk3YTIwZTU2NTYzYmY0MzlkNDZiNGU4Y2Y1Y2EzNDFlM2MzNmY0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FqJWHbCKcoKlU8eP6Vpra6beb334_oVZdNGDo4x5zdk)

That's weird, take a look at this file, it's from version 1.5.4 in npm: https://www.npmjs.com/package/bytenode/file/67b5f06b0fb3f124eed4c381c2515e315fb32637052f933954162a2ba703db15
![image](https://github.com/bytenode/bytenode/assets/20336040/d891a20e-3976-4dff-8ea9-601ac25bf3ed)

[cli.js](https://www.npmjs.com/package/bytenode/file/24a55246e1183b53ec2f926d1d90958e7fb0a813575bf88d3ca8b895a27fea29) in v1.5.3:
![image](https://github.com/bytenode/bytenode/assets/20336040/b4d99b0a-9a1f-4f7f-b89a-18c54449b815)

**Comment by System233** [comment]
Anyway v1.5.4 will not work in the `node:21-alpine3.19` container, just because there are CR newlines in it.

**Comment by OsamaAbbas** [comment]
> That's weird, take a look at this file, it's from version 1.5.4 in npm: https://www.npmjs.com/package/bytenode/file/67b5f06b0fb3f124eed4c381c2515e315fb32637052f933954162a2ba703db15

I downloaded this file, and again, I cannot find any `\r` characters in it.

> `npm pack bytenode@1.5.4`
> Try this command to download the tar.gz package

Again, I downloaded the package, and no `\r` in there.

The images you provided shows that the file is auto-detected to have CR+LF newlines. However, if you actually search for `\r`, you will find none.

> Anyway v1.5.4 will not work in the node:21-alpine3.19 container, just because there are CR newlines in it.

I tested Node v20.x on my machine. I will test Node v21.x later and get back to you.

**Comment by System233** [comment]
This is not possible, maybe you can try to use hex editor or xxd command to view the file in hex mode.
## VSCODE HEX EDITOR
![image](https://github.com/bytenode/bytenode/assets/20336040/b972b862-27f0-4f17-8753-04d9f68bd1ce)

## XXD
$ md5sum cli.js
ed03d365e1dfd03aedc768663b77c569 *cli.js
$ xxd cli.js
00000000: 2321 2f75 7372 2f62 696e 2f65 6e76 206e  #!/usr/bin/env n
00000010: 6f64 65**~~0d~~ 0a~~0d~~ 0a**27 7573 6520 7374 7269  ode....'use stri
00000020: 6374 273b **~~0d~~0a ~~0d~~0a** 636f 6e73 7420 6673  ct';....const fs
00000030: 203d 2072 6571 7569 7265 2827 6673 2729   = require('fs')
00000040: 3b0d 0a63 6f6e 7374 2070 6174 6820 3d20  ;..const path =
00000050: 7265 7175 6972 6528 2770 6174 6827 293b  require('path');

**Comment by OsamaAbbas** [comment]
This is weird. The `md5sum cli.js` from the package is indeed `ed03d365e1dfd03aedc768663b77c569`. However, if you clone the repository and run `md5sum cli.js`, it is `fbea827b80fab18279151221306b238e`.

Now, the most likely reason is that my Git was configured to automatically add CRLF upon checkout and commit LF. So, no CR characters were leaked into the git repository. However, when I used `npm publish`, it packed the local version where the CR characters exist.

But, this does not explain why the version `1.5.4` works on my machine. Maybe it's docker related issue?

Anyways, I will publish a new version now. Let me know if it fixes your issue.

**Comment by System233** [comment]
I tested the v1.5.5 version and now it works fine in the environment, GREAT! 
Thank you for the great work!

Dockerfile:
```Dockerfile
FROM node:21-alpine3.19 as init-env
RUN yarn global add bytenode@1.5.5
```

```shell
docker run -it test sh
/ # bytenode -v
bytenode 1.5.5
Node 21.7.0
/ # vi /usr/local/bin/bytenode ## NO CR newlines now;
```

**Comment by System233** [comment]
I checked cli.js in the repository before and this file is correct, there is no CR newline in it, CR newline only appears in npm packages.
CR newlines may affect shebang instructions in linux, this discussion explains the issue:
https://unix.stackexchange.com/questions/108588/shebang-line-not-working-with-cr-lf
