### ISSUE TITLE
`require` is not defined

### ISSUE THREAD

**Issue by mStirner** [bytenode/bytenode#236]
I have a very simple code:

```js
const {createServer} = require("http");

console.log("Hello World");


const server = createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/plain' });
  res.end('Hello World!\n');
});

// starts a simple http server locally on port 3000
server.listen(3000, '127.0.0.1', () => {
  console.log('Listening on 127.0.0.1:3000');
});


exports = "foo"
```

While compiling it, i get no error and everything seems fine.
When i want to execute the code, i get the following error:

```

> bytenode@1.0.0 start
> node scripts/run.js

evalmachine.<anonymous>:1
"​​​​​​​​​​"
                       ^

ReferenceError: require is not defined
    at evalmachine.<anonymous>:1:24
    at Script.runInThisContext (node:vm:121:12)
    at Object.runBytecode (/home/marc/projects/playground2/bytenode/node_modules/bytenode/lib/index.js:202:17)
    at Object.<anonymous> (/home/marc/projects/playground2/bytenode/scripts/run.js:6:25)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.11.1

```

Related to https://github.com/bytenode/bytenode/issues/230 ?

Whats the correct way to require/include/import other modules?

node 20.11.1
npm: 10.2.4
bytenode: 1.5.6

---

EDIT: 

Tried to run the express example, but i have no `--run` command line argument:
`/home/marc/.nvm/versions/node/v20.11.1/bin/node: bad option: --run`, for what version(s) is the tutorial?

**Comment by OsamaAbbas** [comment]
My initial guess is this: the issue lies in the way you are trying to define `exports` (and the issue here is related to how common js modules work, it's not bytenode related).

You cannot redefine the `exports` variable like you did. Either do this:

```JavaScript
exports.SOME_VALUE = SOME_VALUE;
```

Or this:

```JavaScript
module.exports = SOME_VALUE;
```

You cannot do this:

```JavaScript
exports = SOME_VALUE;
```

So, change your last line to: `module.exports = "foo"` and try again.

**Comment by mStirner** [comment]
Strage...

While getting started with all this, i changed my compile/executing strategies, from a node.js/script based approach, to a "cli based" on.

While the example code above works perfectly fine with `bytenode --compress --compile src/index.js`/`bytenode src/index.jsc`, it fails with the error message when i compile/execute is this way:

__build.js__
```js
const bytenode = require('bytenode');
const fs = require("fs");

const content = fs.readFileSync("./src/index.js", "utf8");
const compiled = bytenode.compileCode(content);

fs.writeFileSync("compiled.jsc", compiled);
```

__run.js__
```js
const bytenode = require('bytenode');
const fs = require("fs");


const content = fs.readFileSync("compiled.jsc");
const result = bytenode.runBytecode(content);

console.log(result)
```

**Comment by OsamaAbbas** [comment]
Here is what you should do:

__build.js__
```js
const bytenode = require('bytenode');

bytenode.compileFile("./src/index.js"); // this compiles the file to ./src/index.jsc
// or
bytenode.compileFile({
  filename: "./src/index.js",
  output: "./path/to/compiled.jsc"
});
```

__run.js__
```js
const bytenode = require('bytenode');

const result = require("./path/to/compiled.jsc");

console.log(result)
```

**Comment by mStirner** [comment]
Thank you very much.
But i have a couple of questions.

1) Why does the code "work" when i use `bytenode --compile ...`
2) Care to explain why use `bytenode.compileFile` instead of `readFileSync` & `bytenode.compileCode` (you do the same in the compileFile method (https://github.com/bytenode/bytenode/blob/2313de58551a4df8994289cad0eb7f4a10232c48/lib/index.js#L254)

**Comment by OsamaAbbas** [comment]
Thank you @mStirner.

**Comment by mStirner** [comment]
I wonder now why i need to compile it as module to use require.
Curious how am i, i wanted to try it with a import statement.

But this fails with (`bytenode -n -c src/index.mjs`):
```
evalmachine.<anonymous>:31
import createServer from "node:http";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (node:vm:99:7)
    at compileCode (/home/marc/.nvm/versions/node/v20.11.1/lib/node_modules/bytenode/lib/index.js:72:18)
    at Object.compileFile (/home/marc/.nvm/versions/node/v20.11.1/lib/node_modules/bytenode/lib/index.js:268:22)
    at /home/marc/.nvm/versions/node/v20.11.1/lib/node_modules/bytenode/lib/cli.js:118:24
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/marc/.nvm/versions/node/v20.11.1/lib/node_modules/bytenode/lib/cli.js:110:17)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
```
Does the node [`vm.Script`](https://nodejs.org/api/vm.html#new-vmscriptcode-options) not support import statements?:
https://github.com/bytenode/bytenode/blob/2313de58551a4df8994289cad0eb7f4a10232c48/lib/index.js#L72
