### ISSUE TITLE
ESM Support

### ISSUE THREAD

**Issue by guyedry1** [bytenode/bytenode#237]
Hi @OsamaAbbas,
Hope you doing well.

Seems many libraries im using are ESM only. wondering if you found a solution to use bytenode in ESM project.

any ideas?
thanks.

**Comment by OsamaAbbas** [comment]
As far as I can tell, this is not possible currently. I explained why in many previous issues, such as #196 and #95.

Also, the alternative is easy: add an extra step in your setup to transpile your ESM code into CommonJS before using Bytenode. CommonJS will not be removed from Node.js, so this option will stay valid as long as Node.js stays relevant.
