### ISSUE TITLE
Add mechanism to supply additional options to node.js process

### ISSUE THREAD

**Issue by travispaul** [bytenode/bytenode#240]
Some Node.js command line options such as `--experimental-permission` cannot be set via the [NODE_OPTIONS](https://nodejs.org/api/cli.html#node_optionsoptions) environment variable. I would like to be able to set such options when running bytenode.

For example, by using an environment variable:

```sh
export BYTENODE_NODE_OPTIONS="--experimental-permission --allow-fs-write=/foo --allow-fs-read=/bar"
bytenode foo.jsc
```

Which _might_ be implemented roughly like this in [cli.js](https://github.com/bytenode/bytenode/blob/master/lib/cli.js#L192):
```diff
diff --git a/lib/cli.js b/lib/cli.js
index 1e556f8..f4b898a 100755
--- a/lib/cli.js
+++ b/lib/cli.js
@@ -191,10 +191,16 @@ if (program.flags.includes('--compile')) {
   }
 } else {
   try {
-    const result = spawnSync(program.nodeBin, [
+    let nodeArgs = []
+    if (process.env.BYTENODE_NODE_OPTIONS) {
+      nodeArgs = process.env.BYTENODE_NODE_OPTIONS.split(' ')
+    }
+    const allArgs = nodeArgs.concat([
       '-r',
       path.resolve(__dirname, 'index.js')
-    ].concat(args), {
+    ])
+    .concat(args)
+    const result = spawnSync(program.nodeBin, allArgs, {
       stdio: 'inherit'
     });
     process.exit(result.status);
```

I can open a more thorough PR if this approach seems reasonable.

**Comment by OsamaAbbas** [comment]
Why not just set it directly from the bytenode cli? It should be possible, any flags unused by bytenode are delegated to node itself.

**Comment by travispaul** [comment]
@OsamaAbbas that would be the ideal scenario. I was having issues with that but perhaps I was holding it wrong, will try again this weekend and report back. Thanks

**Comment by travispaul** [comment]
@OsamaAbbas indeed this seems to work as you described:
```
bytenode [node args] [script] [script args]
```
e.g.
```
bytenode --experimental-permission --allow-fs-write=/foo --allow-fs-read=/bar index.jsc arg1 --foo
```

Sorry for the noise.
