### ISSUE TITLE
Issue when using Dynmaic Import

### ISSUE THREAD

**Issue by hamidpro** [bytenode/bytenode#242]
Hello, I am using dynamic import to use @xenova/transformers which is es module in commonjs 

ERROR

`node:internal/modules/esm/utils:228`
  throw new ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING();
        ^

TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:228:9)
    at eval (eval at <anonymous> (evalmachine.<anonymous>:1:140), <anonymous>:3:1)
    at Object.<anonymous> (evalmachine.<anonymous>:1:189)
    at Module._extensions.<computed> [as .jsc] (/Users/Shared/Final ideas/chat-with-pdf-project/server/testing/server/node_modules/bytenode/lib/index.js:334:26)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING'
}

Node.js v20.16.0
`

<img width="992" alt="Screenshot 2024-09-17 at 14 14 20" src="https://github.com/user-attachments/assets/f32fce43-84ed-4783-830d-6afdb7e06a45">

Code used 
`const USED_MODEL_PROD = "Xenova/gpt2";

const TransformersApi = Function('return import("@xenova/transformers")')();

async function getPipeline() {
    console.log("getPipeline", USED_MODEL_PROD)

    const { pipeline } = await TransformersApi;

    pipeline('text-generation', USED_MODEL_PROD, {
        device: 'gpu', // should be gpu
        streaming: true, // should be true
        return_full_text: false, // should be false
    });

}

getPipeline().then((pipeline) => {
    console.log("pipeline", pipeline)
})

`

My goal is to hide the source code, how can I fix it or is there an other alternative please?
cc @OsamaAbbas

**Comment by OsamaAbbas** [comment]
Bytenode cannot be used with ES Modules, only CommonJS. So, neither `import` keyword nor the dynamic `import()` function would work.

**Comment by SDAdham** [comment]
Hello @OsamaAbbas ,

I've been using bytenode with ES modules for a long time, however since adding a code that dynamically imports another application's library, it fails with the error above, is there any way that we can hack this?
