### ISSUE TITLE
ReferenceError: require is not defined (SEA)

### ISSUE THREAD

**Issue by OvercookedBeef** [bytenode/bytenode#243]
Hi, If my compiled script uses `require` I get the following error: `ReferenceError: require is not defined`
I have read the other issues about using `runBytecode` / `runBytecodeFile`, and the recommendation seems to be to use `require` on the `.jsc` file. But the problem is that with [Single executable applications (SEA)](https://nodejs.org/api/single-executable-applications.html) you can only use `require` on node built-in modules. But, they do allow embedding assets, such as the `.jsc` file.

Essentially, I have a loader:
```js
const sea = require('node:sea');
const bytenode = require('bytenode');

let data;
let buffer;
if (sea.isSea()) {
    data = sea.getRawAsset('main.jsc');
    // We need to copy the buffer or else we get a segmentation fault
    const uint8Array = new Uint8Array(data);
    buffer = Buffer.from(uint8Array);
} else {
    data = require('fs').readFileSync('dist/main.jsc');
    buffer = Buffer.from(data);
}

bytenode.runBytecode(buffer);
```

Of course I could use require in the loader when `sea.isSea()` is false, but that won't work when it is a sea.

and my actual script: (built using `npx bytenode --compile dist/main.js --no-module`)
```js
const sea = require('node:sea');
console.log('SEA: ' + sea.isSea());
```

If I built as a module and instead use `bytenode.runBytecode(buffer)()`, I get a similar error: `TypeError: undefined is not a function` (I believe at the same spot)

Both are also run through webpack, since SEA require deps to be bundled (like bytenode), but of course webpack doesn't bundle node built-in modules so that doesn't help here.

I've tried quite a lot of different things. Could I get some guidance? Thanks.

**Comment by OsamaAbbas** [comment]
SEA is still under active development. So, bytenode won't support it until it reach some stability.

However, you don't need bytenode here, just use their `useCodeCache` as explained [here](https://nodejs.org/api/single-executable-applications.html#v8-code-cache-support).

**Comment by OvercookedBeef** [comment]
> SEA is still under active development. So, bytenode won't consider supporting it until it reaches some stability.
> 
> However, you don't need bytenode here, just use their `useCodeCache` as explained [here](https://nodejs.org/api/single-executable-applications.html#v8-code-cache-support).

Unfortunately even with `"useCodeCache": true` in my config, you can still just run `strings` on the executable and view the raw source code (including comments, of course they could be stripped away though)

**Comment by zsxsoft** [comment]
@OsamaAbbas If I added SEA support, can I create a PR?

**Comment by zsxsoft** [comment]
@OsamaAbbas
I used `pkg` before, but `pkg` is deprecated, so it seems I can only use SEA now. SEA's `useCodeCache` will attach the v8 bytecode after js file, so bytenode is still needed. 

In this case, I have to add the code 
```js
if (sea.isSea()) {
  const asset = sea.getRawAsset(FILENAME_DEFINED_IN_sea-config.json)
  const newAsset = new ArrayBuffer(asset.byteLength) // the blob read by getRawAsset is immutable 
  new Uint8Array(newAsset).set(new Uint8Array(asset))
  realRun(Buffer.from(newAsset)) // A copy of `Module._extensions[COMPILED_EXTNAME]` without readFileSync
}
```

sea-config.json:
```json
{
    "main": "bytenode/loader.js",
    "disableExperimentalSEAWarning": true,
    "useSnapshot": false,
    "useCodeCache": true,
    "output": "sea-prep.blob",
    "assets": {
        "my-code.jsc": "my-code.jsc"
    }
}
```

Then 
```bash
bytenode -c my-code.js -o my-code.jsc
node --experimental-sea-config sea-config.json
npx postject node NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
./node
```

This works.
