### ISSUE TITLE
Cross-platform bytenode

### ISSUE THREAD

**Issue by thanhle7** [bytenode/bytenode#244]
Is there any way to make jsc file cross-platform?
For instance, I compile the file on Windows, then run it with node on Linux.

**Comment by OvercookedBeef** [comment]
Unless you also require cross-compiling, you could make a loader that loads a different .jsc depending on the platform. For compiling for different platforms there is WSL2/Wine or VMs.

**Comment by OsamaAbbas** [comment]
> For instance, I compile the file on Windows, then run it with node on Linux.

That way you described it, isn't possible and will never be possible unless v8 itself support such a thing.
