### ISSUE TITLE
TypeError in Middleware When Using Bytenode with NestJS

### ISSUE THREAD

**Issue by tbareich** [bytenode/bytenode#245]
# Issue: TypeError in Middleware When Using Bytenode with NestJS

## Description
In a NestJS backend project, after creating a custom middleware (`SessionMiddleware`) and bundling the project with Webpack and Bytenode, a `TypeError: Class constructor SessionMiddleware cannot be invoked without 'new'` is encountered when attempting to run an endpoint that uses the middleware.

## Project Details

**Environment**:
- **Node.js**: v20.18.0
- **npm**: v10.8.2
- **pnpm**: v9.9.0
- **NestJS CLI**: v10.4.5
- **Bytenode**: v1.5.6

### Middleware Code

```typescript
import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';
import { SessionService } from './session.service';

@Injectable()
export class SessionMiddleware implements NestMiddleware {
  constructor(private sessionService: SessionService) {}

  async use(req: Request, res: Response, next: NextFunction) {
    // Middleware logic to validate and process session data
    next();
  }
}
```

### Middleware Registration in Module

```typescript
import { Module, MiddlewareConsumer, RequestMethod } from '@nestjs/common';
import { AuthController } from './auth.controller';
import { SessionMiddleware } from './session.middleware';

@Module({
  controllers: [AuthController],
  providers: [SessionMiddleware],
})
export class AuthModule {
  configure(consumer: MiddlewareConsumer) {
    consumer.apply(SessionMiddleware).forRoutes(AuthController);
  }
}
```

### Webpack Configuration

The project is bundled with Webpack and includes Bytenode to create an executable file. Below is the Webpack configuration used:

```javascript
const path = require('path');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const webpack = require('webpack');
const BytenodeWebpackPlugin = require('@herberttn/bytenode-webpack-plugin');

const WebPackIgnorePlugin = {
  checkResource: function (resource) {
    const lazyImports = [
      '@nestjs/platform-express',
      '@nestjs/terminus',
      '@nestjs/swagger',
      'class-transformer',
      'class-validator',
      'oracledb',
    ];
    if (!lazyImports.includes(resource)) return false;
    try {
      require.resolve(resource);
    } catch (err) {
      return true;
    }
    return false;
  },
};

module.exports = {
  mode: 'production',
  target: 'node',
  entry: {
    server: './src/main.ts',
  },
  devtool: 'source-map',
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: {
          loader: 'ts-loader'
        },
        exclude: /node_modules/,
        include: [path.resolve(__dirname, 'src')],
      },
    ],
  },
  resolve: {
    extensions: ['.tsx', '.ts', '.js'],
  },
  node: {
    dirname: false,
  },
  plugins: [
    new CleanWebpackPlugin(),
    new webpack.IgnorePlugin(WebPackIgnorePlugin),
    new BytenodeWebpackPlugin({ keepSource: true }),
  ],
  optimization: {
    minimize: false,
  },
  performance: {
    maxEntrypointSize: 1000000000,
    maxAssetSize: 1000000000,
  },
  output: {
    path: path.resolve(__dirname, 'prod'),
    filename: '[name].js',
  },
};
```

### package.json Overview

**Scripts**:
- **Build**: `nest build`
- **Run**: `start`, `start:dev`, `start:prod`, `start:executable`, `start:obfuscated`
- **Testing & Linting**: `test`, `test:watch`, `test:cov`, `lint`
- **Obfuscation**: `build:obfuscated`

**Dependencies**:
  - **NestJS Modules**: `@nestjs/core`, `@nestjs/common`, `@nestjs/platform-express`, `@nestjs/jwt`, etc.
  - **Databases**: `pg`, `typeorm`, `redis`, `cache-manager`, etc.
  - **Utilities**: `bcrypt`, `axios`, `morgan`, `winston`, etc.
  - **Web Security**: `passport`, `passport-jwt`, `passport-local`

**DevDependencies**:
  - **Build Tools**: `webpack`, `webpack-cli`, `ts-loader`
  - **Testing & Linting**: `jest`, `eslint`, `typescript`
  - **Obfuscation**: `javascript-obfuscator`, `@herberttn/bytenode-webpack-plugin`

### Error

Upon calling an endpoint that uses the `SessionMiddleware`, the following error is thrown:

```
TypeError: Class constructor SessionMiddleware cannot be invoked without 'new'
    at Object.use (/path/to/@nestjs/core/middleware/utils.js:64:24)
    at /path/to/@nestjs/core/router/router-proxy.js:9:23
    ...
```

### Expected Behavior
The `SessionMiddleware` should initialize and handle requests as expected without errors.

### Actual Behavior
The middleware fails to instantiate due to a `TypeError`, indicating that the class constructor cannot be invoked without `new`.

### Additional Context

- The issue occurs only after bundling with Webpack and using Bytenode.
- Without Bytenode, the project works as expected.

### Steps Tried for Troubleshooting

- Verified dependencies for lazy loading with Webpack Ignore Plugin.
- Confirmed middleware works when not bundled with Bytenode.

**Comment by OsamaAbbas** [comment]
@herberttn Can you look into this issue please?

**Comment by herberttn** [comment]
@tbareich could you create a repo with a sample project for me to test this? I'm not familiar with NestJS projects.

**Comment by tbareich** [comment]
> @tbareich could you create a repo with a sample project for me to test this? I'm not familiar with NestJS projects.

You can find the repository here: https://github.com/tbareich/nestjs-middleware. Please take a look at the README file.

**Comment by OsamaAbbas** [comment]
I guess I found the cause of the error. I will make some tests and get back to this issue.

**Comment by OsamaAbbas** [comment]
The issue is that `node_modules/@nestjs/core/middleware/utils.js` uses the `.toString()` function to test where a middleware is a class or not. Bytenode removes the source code, so the test returns false here.

To solve the problem, add a static method to your middleware class:

```JavaScript
static toString() {
    return 'class LoggerMiddleware';
  }
```

**Comment by tbareich** [comment]
Thank you very much, Mr. @OsamaAbbas . I really appreciate your help 🙏
